spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shippingsystem?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: '123456'
server:
  port: 8181

mybatis:
  #    config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
    classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl